apiVersion: v1
kind: Service
metadata:
  name: {{ include "stirling.fullname" . }}
  labels:
    {{- include "stirling.labels" . | nindent 4 }}
    app.kubernetes.io/component: stirling-pdf
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stirling.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: stirling-pdf
