"""Constants for the ExcelParser project"""

from typing import Dict, List
from excel_game import ExcelPlatform

PLATFORM_NAMES: Dict[ExcelPlatform, List[str]] = {
    ExcelPlatform._3DO: ["3do interactive multiplayer"],
    ExcelPlatform.ACORN_ARCHIMEDES: ["archimedes", "arch", "acorn 32-bit"],
    ExcelPlatform.ACORN_ATOM: ["atom"],
    ExcelPlatform.ACORN_ELECTRON: ["electron", "elec"],
    ExcelPlatform.ACTION_MAX: ["am", "actionmax", "wow action max", "amax"],
    ExcelPlatform.AMAZON_FIRE_TV: ["fire", "fire tv", "firetv", "amazon tv", "android"],
    ExcelPlatform.AMSTRAD_CPC: ["cpc"],
    ExcelPlatform.AMSTRAD_PCW: ["pcw"],
    ExcelPlatform.ANDROID: ["and", "andr"],
    ExcelPlatform.APPLE_II: ["apple iigs", "apl2", "apple 2", "ap2"],
    ExcelPlatform.APPLE_IIGS: ["apple iigs", "apl2", "apple 2", "apple 2gs", "iigs"],
    ExcelPlatform.APPLE_III: ["apl3", "ap3"],
    ExcelPlatform.ARCADE: [
        "arc",
        "arcade games",
        "hyper neo geo 64",
        "namco system 22",
        "sammy atomiswave",
        "sega hikaru",
        "sega model 1",
        "sega model 2",
        "sega model 3",
        "sega naomi",
        "sega naomi 2",
        "sega st-v",
        "sega system 16",
        "sega system 32",
        "sega triforce",
        "taito type x",
        "arcd",
    ],
    ExcelPlatform.ARCADIA_2001: ["arcadia", "a2k1", "a2001", "emerson arcadia 2001"],
    ExcelPlatform.ARDUBOY: ["ardu", "arbo"],
    ExcelPlatform.ATARI_2600: ["2600", "a2600", "vcs"],
    ExcelPlatform.ATARI_5200: ["5200", "a5200"],
    ExcelPlatform.ATARI_7800: ["7800", "a7800"],
    ExcelPlatform.ATARI_8_BIT: [
        "atari xe",
        "atari 400/800",
        "a800",
        "atari xe",
        "atari 800",
        "atari 400",
        "a400",
    ],
    ExcelPlatform.ATARI_JAGUAR: ["jaguar", "jag", "atari jaguar cd", "jaguar cd"],
    ExcelPlatform.ATARI_JAGUAR_CD: ["atari jaguar cd", "jaguar cd", "jcd", "jaguarcd"],
    ExcelPlatform.ATARI_LYNX: ["lynx"],
    ExcelPlatform.ATARI_ST: ["ast", "st", "atari st/ste"],
    ExcelPlatform.BANDAI_PIPPIN: ["pip", "pippin", "apple pippin", "pipn"],
    ExcelPlatform.BBC_MICRO: ["bbc", "bbc microcomputer system"],
    ExcelPlatform.BREW: ["mobile", "mobi", "legacy mobile device", "mob"],
    ExcelPlatform.BROWSER: [
        "web browser",
        "online/browser",
        "webonly",
        "fla",
        "flash",
        "web",
        "www",
    ],
    ExcelPlatform.BS_X: [
        "satellaview",
        "snes",
        "super nintendo",
        "super nintendo entertainment system",
        "super famicom",
        "sfc",
        "super nintendo (snes)",
        "nintendo satellaview",
    ],
    ExcelPlatform.CASIO_LOOPY: ["cl", "loopy"],
    ExcelPlatform.COLECO_ADAM: ["adam"],
    ExcelPlatform.COLECOVISION: ["cvis", "col"],
    ExcelPlatform.COMMODORE_64: ["c64", "commodore c64/128/max"],
    ExcelPlatform.COMMODORE_AMIGA: ["amiga", "ami", "ocs", "aga"],
    ExcelPlatform.COMMODORE_AMIGA_CD32: ["amiga cd32", "cd32", "amiga", "ami"],
    ExcelPlatform.COMMODORE_PET: ["pet", "commodore pet/cbm"],
    ExcelPlatform.COMMODORE_PLUS_4: [
        "c-plus-4",
        "cp4",
        "commodore p4",
        "commodore 16, plus/4",
        "commodore plus 4",
        "c16",
    ],
    ExcelPlatform.COMMODORE_VIC_20: ["vic-20", "vic20", "vc20", "vic"],
    ExcelPlatform.DEDICATED_CONSOLE: [
        "television game",
        "dedicated",
        "plug & play",
        "plug and play",
        "ded",
        "lcd game",
        "nintendo game & watch",
        "game & watch",
        "various",
        "wtch",
    ],
    ExcelPlatform.DOJA: ["mobile"],
    ExcelPlatform.DRAGON_32_64: ["dragon", "dragon 32", "dragon 64", "d32", "d64"],
    ExcelPlatform.DSIWARE: ["nintendo dsi", "dsi", "ds", "nintendo ds", "dsiw"],
    ExcelPlatform.DVD_PLAYER: ["dvd"],
    ExcelPlatform.EPOCH_SUPER_CASSETTE_VISION: [
        "super cassette vision",
        "scv",
        "s. cassette vision",
        "scve",
    ],
    ExcelPlatform.E_READER: [
        "nintendo game boy advance",
        "gba",
        "gameboy advance",
        "gameboy advance video",
        "e reader",
        "ereader",
        "erdr",
    ],
    ExcelPlatform.EVERCADE: ["ever cade", "evc"],
    ExcelPlatform.EXEN: ["mobile"],
    ExcelPlatform.EXIDY_SORCERER: ["exidy", "sorcerer"],
    ExcelPlatform.FAMICOM_DISK_SYSTEM: [
        "fds",
        "family computer disk system",
        "famicomds",
        "nintendo famicom disk system",
        "fdsy",
    ],
    ExcelPlatform.FM_TOWNS: [
        "fmt",
        "fm towns marty",
        "fmtowns",
        "fujitsu fm towns",
        "fujitsu fm towns marty",
    ],
    ExcelPlatform.FM_7: ["fujitsu fm-7", "fujitsu micro 7", "micro 7", "fm7"],
    ExcelPlatform.GALAKSIJA: [],
    ExcelPlatform.GAMATE: ["gmte"],
    ExcelPlatform.GAME_BOY: ["nintendo game boy", "gb", "gameboy"],
    ExcelPlatform.GAME_BOY_ADVANCE: [
        "nintendo game boy advance",
        "gba",
        "gameboy advance",
        "gameboy advance video",
    ],
    ExcelPlatform.GAME_BOY_COLOR: ["nintendo game boy color", "gbc", "gameboy color"],
    ExcelPlatform.GAME_COM: ["tiger game.com", "gcom", "gamecom", "tig"],
    ExcelPlatform.GAMEPARK_32: ["gp32", "gamepark gp32"],
    ExcelPlatform.GIZMONDO: ["giz", "gizm"],
    ExcelPlatform.GOOGLE_STADIA: ["stadia", "sta", "std"],
    ExcelPlatform.GP2X: [],
    ExcelPlatform.GP2X_CAANOO: ["gp2x", "caanoo"],
    ExcelPlatform.GP2X_WIZ: ["gp2x", "wiz"],
    ExcelPlatform.HARTUNG_GAME_MASTER: ["game master", "gmas"],
    ExcelPlatform.HYPERSCAN: ["mattel hyperscan", "hyp", "hyper scan", "hscan"],
    ExcelPlatform.INTELLIVISION: ["intv"],
    ExcelPlatform.IOS: [
        "iphone",
        "iphn",
        "ipad",
        "ios (iphone/ipad)",
        "mobile",
        "apple ios",
    ],
    ExcelPlatform.IPOD: ["ipod classic", "ipod touch"],
    ExcelPlatform.J2ME: ["mobile", "mobi", "legacy mobile device", "mob"],
    ExcelPlatform.LASERDISC: ["ld", "msx"],
    ExcelPlatform.MAC_OS: [
        "macintosh",
        "mac",
        "macos",
        "classic mac os",
        "classic macos",
        "apple mac os",
        "apple macos",
        "osx",
    ],
    ExcelPlatform.MAGNAVOX_ODYSSEY_2: [
        "odyssey 2",
        "odyssey2",
        "odyssey^2",
        "o2",
        "ody2",
    ],
    ExcelPlatform.MAINFRAME: ["pdp10", "pc", "mfrm"],
    ExcelPlatform.MATTEL_AQUARIUS: ["aqu", "aquarius", "aqrs"],
    ExcelPlatform.MEGA_DUCK: ["cougar boy", "mgd", "mega-duck"],
    ExcelPlatform.MICROVISION: ["mvis", "mcrv"],
    ExcelPlatform.MONON_COLOR: [],
    ExcelPlatform.MOPHUN: ["mobile", "mobi", "legacy mobile device", "mob"],
    ExcelPlatform.MSX: ["microsoft msx"],
    ExcelPlatform.MSX_TURBO_R: [
        "msx",
        "turbo-r",
        "turbo r",
        "msx turbo r",
        "microsoft msx",
    ],
    ExcelPlatform.MSX2: [
        "msx",
        "msx 2",
        "msx 2+",
        "msx2+",
        "microsoft msx2",
        "microsoft msx2+",
    ],
    ExcelPlatform.N_GAGE: ["ngage", "nge", "nokia n-gage", "ngge"],
    ExcelPlatform.N_GAGE_2_0: ["n-gage", "ngage", "n-gage (service)", "nge"],
    ExcelPlatform.NEC_PC_6001: [
        "pc-6001",
        "pc6001",
        "pc60",
        "pc-60",
        "nec pc60",
        "nec pc-60",
        "nec pc6001",
        "nec pc-6001",
        "6001",
        "pc-6000 series",
        "p6000",
        "p60",
        "p61",
    ],
    ExcelPlatform.NEC_PC_8801: [
        "pc-8801",
        "pc88",
        "pc-88",
        "nec pc88",
        "nec pc-88",
        "pc-8800 series",
        "p88",
        "8001",
        "8801",
    ],
    ExcelPlatform.NEC_PC_9801: [
        "pc-9801",
        "pc98",
        "pc-98",
        "nec pc98",
        "nec pc-98",
        "pc-9800 series",
        "p98",
        "9801",
    ],
    ExcelPlatform.NEO_GEO: [
        "neogeo",
        "neo geo",
        "neo",
        "ng",
        "neo geo aes",
        "neo geo mvs",
        "snk neo geo aes",
        "snk neo geo mvs",
    ],
    ExcelPlatform.NEO_GEO_CD: [
        "neogeo",
        "neo geo",
        "neogeo cd",
        "ncd",
        "ngcd",
        "neo geo cd",
        "neogeocd",
        "snk neo geo cd",
    ],
    ExcelPlatform.NEO_GEO_POCKET: [
        "ngp",
        "neogeo pocket",
        "neo geo pocket",
        "snk neo geo pocket",
    ],
    ExcelPlatform.NEO_GEO_POCKET_COLOR: [
        "ngpc",
        "neogeo pocket color",
        "neo geo pocket color",
        "snk neo geo pocket color",
    ],
    ExcelPlatform.NES: [
        "famicom",
        "nintendo entertainment system",
        "family computer",
        "nintendo",
        "nintendo (nes)",
    ],
    ExcelPlatform.NEW_NINTENDO_3DS: [
        "nintendo 3ds",
        "3ds",
        "nintendo 3ds eshop",
        "n3d",
        "virtual console 3ds",
    ],
    ExcelPlatform.NINTENDO_3DS: [
        "3ds",
        "nintendo 3ds eshop",
        "3dse",
        "virtual console 3ds",
    ],
    ExcelPlatform.NINTENDO_64: ["n64"],
    ExcelPlatform.NINTENDO_64DD: ["64dd", "n64dd", "n64d"],
    ExcelPlatform.NINTENDO_DS: ["nds", "ds"],
    ExcelPlatform.NINTENDO_DSI: ["dsi", "nds", "ds"],
    ExcelPlatform.NINTENDO_GAMECUBE: ["gcn", "gamecube", "gc", "gcube"],
    ExcelPlatform.NINTENDO_POKEMON_MINI: [
        "pokemon mini",
        "pokémon mini",
        "nintendo pokemon mini",
        "pmini",
        "pmm",
        "pokemon-mini",
    ],
    ExcelPlatform.NINTENDO_SWITCH: [
        "switch",
        "ns",
        "swi",
        "nintendo switch online",
        "swtc",
    ],
    ExcelPlatform.NINTENDO_SWITCH_2: ["switch 2", "ns2", "sw2", "switch-2", "swi2"],
    ExcelPlatform.NINTENDO_WII: ["wii", "wii shop", "virtual console wii"],
    ExcelPlatform.NINTENDO_WII_U: [
        "wii u",
        "wiiu",
        "wii u eshop",
        "wiiu eshop",
        "nintendo wii u eshop",
        "wiu",
        "wii-u",
        "virtual console wiiu",
    ],
    ExcelPlatform.NUON: ["dvd", "dvd player"],
    ExcelPlatform.OCULUS_QUEST: [
        "oq",
        "oculus vr",
        "quest",
        "meta quest",
        "mq",
        "meta-quest",
        "meta quest 2",
        "meta quest pro",
        "meta quest 3",
    ],
    ExcelPlatform.ORIC: ["oric 1/atmos", "oric 1", "oric atmos", "oric1"],
    ExcelPlatform.OS_2: ["os2", "ibm os2", "ibm os/2", "os 2", "ibm os 2"],
    ExcelPlatform.OUYA: [],
    ExcelPlatform.PALM_OS: [
        "palmos",
        "palm webos",
        "palm web os",
        "pos",
        "wos",
        "palm os classic",
        "palm-webos",
        "palm",
    ],
    ExcelPlatform.PC: [
        "windows pc",
        "windows",
        "dos",
        "pc (microsoft windows)",
        "msdos",
        "ms-dos",
        "steamvr",
        "msd",
        "win",
        "microsoft windows",
        "steam deck",
        "scummvm",
        "windows 3.x",
        "w31",
        "wce",
    ],
    ExcelPlatform.PC_FX: ["pcfx", "pcf", "nec pc-fx"],
    ExcelPlatform.PHILIPS_CD_I: ["cdi", "cd-i"],
    ExcelPlatform.PIONEER_LASERACTIVE: ["laseractive", "la", "laser", "lmld"],
    ExcelPlatform.PLAYDATE: ["pd", "plde"],
    ExcelPlatform.PLAYDIA: ["pld", "bandai playdia"],
    ExcelPlatform.PLAYSTATION: [
        "psx",
        "ps1",
        "sony playstation",
        "ps",
        "playstation 1",
        "sony playstation 1",
        "psone classics",
    ],
    ExcelPlatform.PLAYSTATION_2: ["ps2", "sony playstation 2"],
    ExcelPlatform.PLAYSTATION_3: [
        "ps3",
        "sony playstation 3",
        "playstation network (ps3)",
    ],
    ExcelPlatform.PLAYSTATION_4: [
        "ps4",
        "sony playstation 4",
        "playstation vr",
        "psvr",
    ],
    ExcelPlatform.PLAYSTATION_5: [
        "ps5",
        "sony playstation 5",
        "playstation vr2",
        "psvr2",
    ],
    ExcelPlatform.PLAYSTATION_NETWORK: [
        "psn",
        "ps3",
        "sony playstation 3",
        "playstation 3",
        "playstation 4",
        "sony playstation 4",
        "playstation portable",
        "psp",
        "ps4",
        "sony playstation portable",
        "sony psp",
        "playstation vita",
        "psvita",
        "vita",
        "ps vita",
        "psv",
        "sony playstation vita",
        "sony ps vita",
        "playstation network (vita)",
        "playstation network (psp)",
        "playstation network (ps3)",
    ],
    ExcelPlatform.PLAYSTATION_PORTABLE: [
        "psp",
        "sony playstation portable",
        "sony psp",
        "sony psp minis",
        "playstation network (psp)",
    ],
    ExcelPlatform.PLAYSTATION_VITA: [
        "psvita",
        "vita",
        "ps vita",
        "psv",
        "sony playstation vita",
        "sony ps vita",
        "playstation network (vita)",
    ],
    ExcelPlatform.R_ZONE: [
        "rzone",
        "lcd game",
        "dedicated handheld",
        "dedicated console",
        "rzne",
    ],
    ExcelPlatform.RISC_PC: [
        "acorn archimedes",
        "archimedes",
        "arch",
        "acorn 32-bit",
        "risc",
    ],
    ExcelPlatform.SEGA_32X: ["32x", "s32x", "sega cd 32x"],
    ExcelPlatform.SEGA_CD: ["scd", "sega cd 32x"],
    ExcelPlatform.SEGA_DREAMCAST: ["dreamcast", "dcast", "dc"],
    ExcelPlatform.SEGA_GAME_GEAR: ["gg", "game gear", "gamegear", "sega gamegear"],
    ExcelPlatform.SEGA_GENESIS: [
        "genesis",
        "mega drive",
        "sega mega drive",
        "gen",
        "md",
        "sega mega drive/genesis",
        "megadrive",
    ],
    ExcelPlatform.SEGA_MASTER_SYSTEM: [
        "sms",
        "master system",
        "sega master system/mark iii",
        "ms",
    ],
    ExcelPlatform.SEGA_PICO: ["pico"],
    ExcelPlatform.SEGA_SATURN: ["saturn", "sat"],
    ExcelPlatform.SEGA_SG_1000: ["sg-1000", "sg1000", "sega sg1000", "sg1", "sg1k"],
    ExcelPlatform.SHARP_X1: ["x1", "sx1", "sx1z"],
    ExcelPlatform.SHARP_X68000: ["x68000", "x68k", "sharp x68k", "x68"],
    ExcelPlatform.SNES: [
        "super famicom",
        "super nintendo entertainment system",
        "sfc",
        "super nintendo",
        "super nes",
        "nintendo power",
    ],
    ExcelPlatform.SUPER_ACAN: [
        "super acan",
        "super a can",
        "acan",
        "a'can",
        "acan",
        "sac",
        "superacan",
        "funtech super acan",
    ],
    ExcelPlatform.SUPERGRAFX: [
        "nec supergrafx",
        "sgfx",
        "sg",
        "turbografx-16",
        "tg16",
        "turbografx16",
        "pce",
        "pc engine",
        "pce engine supergrafx",
        "turbografx-16/pc engine cd",
        "turbografx-16/pc engine",
        "turbografx 16",
        "pc engine supergrafx",
    ],
    ExcelPlatform.SYMBIAN: ["mobile", "mobi", "legacy mobile device", "mob"],
    ExcelPlatform.TAPWAVE_ZODIAC: ["zodiac", "zod"],
    ExcelPlatform.THUMBY: [],
    ExcelPlatform.THUMBY_COLOR: [],
    ExcelPlatform.TI_99_4A: [
        "ti-99",
        "ti-994a",
        "ti99",
        "ti",
        "texas instruments ti 99/4a",
    ],
    ExcelPlatform.TIMETOP_GAMEKING: [
        "gameking",
        "timetop",
        "game king",
        "game king i / ii / iii",
        "gmkn",
    ],
    ExcelPlatform.TIMETOP_GAMEKING_III: [
        "timetop",
        "gameking iii",
        "gameking 3",
        "gameking3",
        "game king",
        "game king i / ii / iii",
        "game king 3",
        "game king iii",
    ],
    ExcelPlatform.TRS_80_COLOR_COMPUTER: [
        "trs-80",
        "trs-80 cc",
        "trs80",
        "color computer",
        "trs-80 color",
        "trs 80 color",
        "trs 80 color computer",
        "trs 80",
        "coco",
        "tandy color computer",
        "tandy coco",
        "trs-80 coco",
        "tandy trs-80",
    ],
    ExcelPlatform.TURBOGRAFX_16: [
        "tg16",
        "turbografx16",
        "pce",
        "pc engine",
        "pce engine supergrafx",
        "turbografx-16/pc engine cd",
        "turbografx-16/pc engine",
        "turbografx 16",
        "nec turbografx-16",
    ],
    ExcelPlatform.TURBOGRAFX_CD: [
        "tcd",
        "turbo cd",
        "turbo-cd",
        "turbografxcd",
        "pc engine cd-rom",
        "pc engine cd-rom²",
        "turbografx 16 cd",
        "turbocd",
        "nec turbografx-cd",
        "pecd",
    ],
    ExcelPlatform.TVOS: [
        "ios",
        "iphone",
        "iphn",
        "ipad",
        "ios (iphone/ipad)",
        "tos",
        "apple tv",
    ],
    ExcelPlatform.VECTREX: ["vecx", "gce vectrex", "vec"],
    ExcelPlatform.VIRTUAL_BOY: [
        "vb",
        "nintendo virtual boy",
        "nintendo vb",
        "vboy",
        "virtualboy",
    ],
    ExcelPlatform.WATARA_SUPERVISION: [
        "supervision",
        "watara/quickshot supervision",
        "sv",
    ],
    ExcelPlatform.WATCHOS: [
        "ios",
        "iphone",
        "iphn",
        "ipad",
        "ios (iphone/ipad)",
        "wos",
    ],
    ExcelPlatform.WIIWARE: [
        "wii",
        "nintendo wii",
        "wii shop",
        "virtual console",
        "vc",
        "ww",
        "virtual console wii",
    ],
    ExcelPlatform.WINDOWS_MOBILE: [
        "mobile",
        "mobi",
        "legacy mobile device",
        "mob",
        "winm",
        "windows-mobile",
    ],
    ExcelPlatform.WINDOWS_PHONE: [
        "mobile",
        "mobi",
        "legacy mobile device",
        "mob",
        "winm",
        "wp",
    ],
    ExcelPlatform.WONDERSWAN: ["ws", "bandai wonderswan"],
    ExcelPlatform.WONDERSWAN_COLOR: ["wsc", "bandai wonderswan color"],
    ExcelPlatform.XBOX: ["xb", "microsoft xbox"],
    ExcelPlatform.XBOX_360: [
        "360",
        "x360",
        "microsoft xbox 360",
        "xbla",
        "xbox live arcade",
        "xblig",
        "xbox live indie games",
        "xbl",
        "xbox 360 games store",
        "xbox360",
    ],
    ExcelPlatform.XBOX_ONE: ["xone", "microsoft xbox one", "xbo", "xboxone", "xbox1"],
    ExcelPlatform.XBOX_SERIES_X_S: [
        "microsoft xbox series x",
        "xbox series",
        "xbox series x/s",
        "xbsx",
        "xbox series x",
        "xbox series s",
        "xs",
        "xxs",
        "xbox-series-x",
        "microsoft xbox series x/s",
    ],
    ExcelPlatform.ZEEBO: ["zb", "zebo"],
    ExcelPlatform.ZX_SPECTRUM: [
        "spectrum",
        "zx",
        "sinclair zx81/spectrum",
        "sinclair zx spectrum",
        "sinclair",
        "spc",
    ],
}
