from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional

# ExcelPlatform enum copied verbatim from zdiemer/GamesMaster src/excel_game.py.
# Its members' values are exactly the platform strings used in the spreadsheet,
# so raw platform cells map via ExcelPlatform(value).

class ExcelPlatform(Enum):
    _3DO = "3DO"
    ACORN_ARCHIMEDES = "Acorn Archimedes"
    ACORN_ATOM = "Acorn Atom"
    ACORN_ELECTRON = "Acorn Electron"
    ACTION_MAX = "Action Max"
    AMAZON_FIRE_TV = "Amazon Fire TV"
    AMSTRAD_CPC = "Amstrad CPC"
    AMSTRAD_PCW = "Amstrad PCW"
    ANDROID = "Android"
    APPLE_II = "Apple II"
    APPLE_IIGS = "Apple IIGS"
    APPLE_III = "Apple III"
    ARCADE = "Arcade"
    ARCADIA_2001 = "Arcadia 2001"
    ARDUBOY = "Arduboy"
    ATARI_2600 = "Atari 2600"
    ATARI_5200 = "Atari 5200"
    ATARI_7800 = "Atari 7800"
    ATARI_8_BIT = "Atari 8-bit"
    ATARI_JAGUAR = "Atari Jaguar"
    ATARI_JAGUAR_CD = "Atari Jaguar CD"
    ATARI_LYNX = "Atari Lynx"
    ATARI_ST = "Atari ST"
    BANDAI_PIPPIN = "Bandai Pippin"
    BBC_MICRO = "BBC Micro"
    BREW = "BREW"
    BROWSER = "Browser"
    BS_X = "BS-X"
    CASIO_LOOPY = "Casio Loopy"
    COLECO_ADAM = "Coleco Adam"
    COLECOVISION = "ColecoVision"
    COMMODORE_64 = "Commodore 64"
    COMMODORE_AMIGA = "Commodore Amiga"
    COMMODORE_AMIGA_CD32 = "Commodore Amiga CD32"
    COMMODORE_PET = "Commodore PET"
    COMMODORE_PLUS_4 = "Commodore Plus/4"
    COMMODORE_VIC_20 = "Commodore VIC-20"
    DEDICATED_CONSOLE = "Dedicated Console"
    DOJA = "DoJa"
    DRAGON_32_64 = "Dragon 32/64"
    DSIWARE = "DSiWare"
    DVD_PLAYER = "DVD Player"
    EPOCH_SUPER_CASSETTE_VISION = "Epoch Super Cassette Vision"
    E_READER = "e-Reader"
    EVERCADE = "Evercade"
    EXEN = "ExEn"
    EXIDY_SORCERER = "Exidy Sorcerer"
    FAMICOM_DISK_SYSTEM = "Famicom Disk System"
    FM_TOWNS = "FM Towns"
    FM_7 = "FM-7"
    GALAKSIJA = "Galaksija"
    GAMATE = "Gamate"
    GAME_BOY = "Game Boy"
    GAME_BOY_ADVANCE = "Game Boy Advance"
    GAME_BOY_COLOR = "Game Boy Color"
    GAME_COM = "Game.com"
    GAMEPARK_32 = "GamePark 32"
    GIZMONDO = "Gizmondo"
    GOOGLE_STADIA = "Google Stadia"
    GP2X = "GP2X"
    GP2X_CAANOO = "GP2X Caanoo"
    GP2X_WIZ = "GP2X Wiz"
    HARTUNG_GAME_MASTER = "Hartung Game Master"
    HYPERSCAN = "HyperScan"
    INTELLIVISION = "Intellivision"
    IOS = "iOS"
    IPOD = "iPod"
    J2ME = "J2ME"
    LASERDISC = "LaserDisc"
    MAC_OS = "Mac OS"
    MAGNAVOX_ODYSSEY_2 = "Magnavox Odyssey 2"
    MAINFRAME = "Mainframe"
    MATTEL_AQUARIUS = "Mattel Aquarius"
    MEGA_DUCK = "Mega Duck"
    MICROVISION = "Microvision"
    MONON_COLOR = "Monon Color"
    MOPHUN = "Mophun"
    MSX = "MSX"
    MSX_TURBO_R = "MSX Turbo R"
    MSX2 = "MSX2"
    N_GAGE = "N-Gage"
    N_GAGE_2_0 = "N-Gage 2.0"
    NEC_PC_6001 = "NEC PC-6001"
    NEC_PC_8801 = "NEC PC-8801"
    NEC_PC_9801 = "NEC PC-9801"
    NEO_GEO = "Neo-Geo"
    NEO_GEO_CD = "Neo-Geo CD"
    NEO_GEO_POCKET = "Neo-Geo Pocket"
    NEO_GEO_POCKET_COLOR = "Neo-Geo Pocket Color"
    NES = "NES"
    NEW_NINTENDO_3DS = "New Nintendo 3DS"
    NINTENDO_3DS = "Nintendo 3DS"
    NINTENDO_64 = "Nintendo 64"
    NINTENDO_64DD = "Nintendo 64DD"
    NINTENDO_DS = "Nintendo DS"
    NINTENDO_DSI = "Nintendo DSi"
    NINTENDO_GAMECUBE = "Nintendo GameCube"
    NINTENDO_POKEMON_MINI = "Nintendo Pokémon mini"
    NINTENDO_SWITCH = "Nintendo Switch"
    NINTENDO_SWITCH_2 = "Nintendo Switch 2"
    NINTENDO_WII = "Nintendo Wii"
    NINTENDO_WII_U = "Nintendo Wii U"
    NUON = "Nuon"
    OCULUS_QUEST = "Oculus Quest"
    ORIC = "Oric"
    OS_2 = "OS/2"
    OUYA = "Ouya"
    PALM_OS = "Palm OS"
    PC = "PC"
    PC_FX = "PC-FX"
    PHILIPS_CD_I = "Philips CD-i"
    PIONEER_LASERACTIVE = "Pioneer LaserActive"
    PLAYDATE = "Playdate"
    PLAYDIA = "Playdia"
    PLAYSTATION = "PlayStation"
    PLAYSTATION_2 = "PlayStation 2"
    PLAYSTATION_3 = "PlayStation 3"
    PLAYSTATION_4 = "PlayStation 4"
    PLAYSTATION_5 = "PlayStation 5"
    PLAYSTATION_NETWORK = "PlayStation Network"
    PLAYSTATION_PORTABLE = "PlayStation Portable"
    PLAYSTATION_VITA = "PlayStation Vita"
    R_ZONE = "R-Zone"
    RISC_PC = "Risc PC"
    SEGA_32X = "Sega 32X"
    SEGA_CD = "Sega CD"
    SEGA_DREAMCAST = "Sega Dreamcast"
    SEGA_GAME_GEAR = "Sega Game Gear"
    SEGA_GENESIS = "Sega Genesis"
    SEGA_MASTER_SYSTEM = "Sega Master System"
    SEGA_PICO = "Sega Pico"
    SEGA_SATURN = "Sega Saturn"
    SEGA_SG_1000 = "Sega SG-1000"
    SHARP_X1 = "Sharp X1"
    SHARP_X68000 = "Sharp X68000"
    SNES = "SNES"
    SUPER_ACAN = "Super A'Can"
    SUPERGRAFX = "SuperGrafx"
    SYMBIAN = "Symbian"
    TAPWAVE_ZODIAC = "Tapwave Zodiac"
    THUMBY = "Thumby"
    THUMBY_COLOR = "Thumby Color"
    TI_99_4A = "TI-99/4A"
    TIMETOP_GAMEKING = "Timetop GameKing"
    TIMETOP_GAMEKING_III = "Timetop GameKing III"
    TRS_80_COLOR_COMPUTER = "TRS-80 Color Computer"
    TURBOGRAFX_16 = "TurboGrafx-16"
    TURBOGRAFX_CD = "TurboGrafx-CD"
    TVOS = "tvOS"
    VECTREX = "Vectrex"
    VIRTUAL_BOY = "Virtual Boy"
    WATARA_SUPERVISION = "Watara SuperVision"
    WATCHOS = "watchOS"
    WIIWARE = "WiiWare"
    WINDOWS_MOBILE = "Windows Mobile"
    WINDOWS_PHONE = "Windows Phone"
    WONDERSWAN = "WonderSwan"
    WONDERSWAN_COLOR = "WonderSwan Color"
    XBOX = "Xbox"
    XBOX_360 = "Xbox 360"
    XBOX_ONE = "Xbox One"
    XBOX_SERIES_X_S = "Xbox Series X|S"
    ZEEBO = "Zeebo"
    ZX_SPECTRUM = "ZX Spectrum"

    def __str__(self) -> str:
        return self.value

    def __repr__(self) -> str:
        return self.__str__()




@dataclass
class ExcelGame:
    """Minimal row adapter the MatchValidator understands."""

    title: str
    platform: Optional[ExcelPlatform] = None
    release_year: Optional[int] = None
    developer: Optional[str] = None
    publisher: Optional[str] = None
    franchise: Optional[str] = None
