apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keepass.fullname" . }}-webdav
  labels:
    {{- include "keepass.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "webdav.auth.username required" .Values.webdav.auth.username | quote }}
  password: {{ required "webdav.auth.password required" .Values.webdav.auth.password | quote }}
