apiVersion: v1
kind: Service
metadata:
  name: {{ include "keepass.fullname" . }}-webdav
  labels:
    {{- include "keepass.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webdav.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "keepass.webdav.selectorLabels" . | nindent 4 }}
