apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "token is required (set it in values.local.yaml)" .Values.token | quote }}
