apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless.fullname" . }}-postgres
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - {{ .Values.persistence.postgres.accessMode }}
  {{- with .Values.persistence.postgres.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.postgres.size }}
