apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.fullname" . }}-postgres
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ required "postgres.password required in values.local.yaml" .Values.postgres.password | quote }}
