apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless.fullname" . }}-redis
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "paperless.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
