apiVersion: v1
kind: Secret
metadata:
  name: {{ include "romm.fullname" . }}-smb-creds
  labels:
    {{- include "romm.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "smb.username required in values.local.yaml" .Values.smb.username | quote }}
  password: {{ required "smb.password required in values.local.yaml" .Values.smb.password | quote }}
