{{- if .Values.imageCredentials.pat }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carson.fullname" . }}-ghcr
  labels:
    {{- include "carson.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.imageCredentials.registry .Values.imageCredentials.username .Values.imageCredentials.pat (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.pat | b64enc) | b64enc }}
{{- end }}
