apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "authelia.fullname" . }}-data
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
