apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloud-game.fullname" . }}-data
  labels:
    {{- include "cloud-game.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
