{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bitmagnet.fullname" . }}
  labels:
    {{- include "bitmagnet.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if .Values.auth.forwardAuth.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "bitmagnet.fullname" . }}-forwardauth@kubernetescrd
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.bitmagnet.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bitmagnet.fullname" . }}
                port:
                  number: {{ .Values.bitmagnet.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.bitmagnet.host }}
  {{- end }}
{{- end }}
