#!/usr/bin/env bash
# Bundle secrets.sh + op-session.sh + the pty helper into one executable.
#
# WHY BUNDLE AT ALL. The tool was only reachable as a path into a checkout —
# `~/Code/selfhosted/scripts/secrets.sh edit infra/duckdns` — which meant it did
# not exist for anyone without that checkout, and was awkward for everyone with
# one. Secrets get rotated when rotating them is easy.
#
# NOT A COMPILED BINARY, and deliberately so. The behaviour here is a year of
# accumulated corrections — op item edit's --template-not-'-' rule, the pty
# sign-in, the merge that stops a push deleting a sibling field, the trailing
# newline. Rewriting that in Go would be re-earning every one of those. This is
# the same code, delivered differently.
#
#   ./scripts/build-secrets-cli.sh            -> dist/secrets
#   ./scripts/build-secrets-cli.sh --install  -> and copy to ~/.local/bin
#
# The output is generated, gitignored, and reproducible: sources stay separate
# and reviewable, and the bundle is rebuilt rather than edited.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "${HERE}/.." && pwd)"
OUT="${OUT:-${ROOT}/dist/secrets}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/.local/bin}"

mkdir -p "$(dirname "$OUT")"

# The pty helper is Python and cannot be sourced. It is embedded base64-encoded
# rather than as a heredoc: it contains its own heredocs and quoting that a
# nested heredoc would mangle, and base64 has no such failure mode.
PTY_B64="$(base64 -w0 < "${ROOT}/scripts/lib/op-signin-pty.py")"

# What this bundle was cut from, so it can notice later that it is behind. The
# copy has no other way to know: it is a file on PATH with no link back to the
# tree it came from. secrets.sh's warn_if_bundle_stale recomputes exactly this,
# over exactly these three files in exactly this order — keep the two in step.
SRC_HASH="$(cat "${ROOT}/scripts/secrets.sh" \
                "${ROOT}/scripts/op-session.sh" \
                "${ROOT}/scripts/lib/op-signin-pty.py" | sha256sum | cut -d' ' -f1)"

{
  cat <<'HEADER'
#!/usr/bin/env bash
# GENERATED by scripts/build-secrets-cli.sh — do not edit.
#
# Sources of truth:
#   scripts/secrets.sh
#   scripts/op-session.sh
#   scripts/lib/op-signin-pty.py
#
# Runs with or without a selfhosted checkout. Vault work (show, edit, check,
# backup, restore) needs none; `new` and `verify` do, and say so.
set -euo pipefail

# The helpers are extracted to tmpfs on every run, never to a disk: one of them
# is handed the account password by path. They go away with the process.
_sc_rt=""
for _d in "${XDG_RUNTIME_DIR:-}" "/run/user/$(id -u)" /dev/shm /tmp; do
  [[ -n "$_d" && -d "$_d" && -w "$_d" ]] || continue
  case "$(stat -f -c %T "$_d" 2>/dev/null)" in tmpfs|ramfs) _sc_rt="$_d"; break ;; esac
done
[[ -n "$_sc_rt" ]] || { echo "secrets: no tmpfs available for the bundled helpers" >&2; exit 1; }
_SC_DIR="$(mktemp -d "${_sc_rt}/secrets-cli.XXXXXX")"; chmod 700 "$_SC_DIR"
_sc_cleanup() { [[ -n "${_SC_DIR:-}" && -d "$_SC_DIR" ]] && rm -rf "$_SC_DIR"; }
trap _sc_cleanup EXIT INT TERM
HEADER

  printf '\nbase64 -d <<%s > "$_SC_DIR/op-signin-pty.py"\n%s\nPTY_EOF\nchmod 700 "$_SC_DIR/op-signin-pty.py"\n' \
    "'PTY_EOF'" "$PTY_B64"

  # Set before secrets.sh is appended; its own `BUNDLE_SRC_HASH="${BUNDLE_SRC_HASH:-}"`
  # keeps this value rather than blanking it. Empty when run from the checkout,
  # which is how the staleness check knows it is looking at a bundle at all.
  printf '\n# sha256 of scripts/secrets.sh + op-session.sh + lib/op-signin-pty.py at build time.\nBUNDLE_SRC_HASH=%s\n' "$SRC_HASH"

  # op-session.sh, verbatim, with its own helper path pointed at the extract.
  printf '\ncat <<%s > "$_SC_DIR/op-session.sh"\n' "'OPSESSION_EOF'"
  sed 's/^/:::/' "${ROOT}/scripts/op-session.sh" | sed 's/^::://'
  printf 'OPSESSION_EOF\nchmod 700 "$_SC_DIR/op-session.sh"\n'

  cat <<'WIRING'

# secrets.sh finds its session helper through this, so the bundle points it at
# the extracted copy instead of a checkout that may not exist.
export OP_SESSION_SH="$_SC_DIR/op-session.sh"
# ...and op-session.sh finds the pty helper the same way.
export OP_PTY_HELPER="$_SC_DIR/op-signin-pty.py"
WIRING

  # secrets.sh itself, minus its shebang and `set -e` (already established).
  echo
  tail -n +2 "${ROOT}/scripts/secrets.sh" | grep -v '^set -euo pipefail$'
} > "$OUT"

chmod 755 "$OUT"
bash -n "$OUT" || { echo "FAIL: generated bundle does not parse"; exit 1; }

echo "==> ${OUT#"$ROOT"/}  ($(wc -c < "$OUT") bytes, $(wc -l < "$OUT") lines)"

if [[ "${1:-}" == "--install" ]]; then
  mkdir -p "$INSTALL_DIR"
  install -m755 "$OUT" "${INSTALL_DIR}/secrets"
  echo "==> installed ${INSTALL_DIR}/secrets"
  case ":$PATH:" in
    *":${INSTALL_DIR}:"*) ;;
    *) echo "    NOTE: ${INSTALL_DIR} is not on \$PATH" ;;
  esac
fi
