apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steam-headless.fullname" . }}
  labels:
    {{- include "steam-headless.labels" . | nindent 4 }}
type: Opaque
stringData:
  # The container user's sudo password (also the noVNC desktop's).
  USER_PASSWORD: {{ required "userPassword required in values.local.yaml" .Values.userPassword | quote }}
  SUNSHINE_PASS: {{ required "sunshine.password required in values.local.yaml" .Values.sunshine.password | quote }}
