{{- $ctx := merge (dict "componentName" "mongo") . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vocard.fullname" $ctx }}
  labels:
    {{- include "vocard.labels" $ctx | nindent 4 }}
spec:
  serviceName: {{ include "vocard.fullname" $ctx }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "vocard.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vocard.labels" $ctx | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mongo
          image: "{{ .Values.images.mongo.repository }}:{{ .Values.images.mongo.tag }}"
          imagePullPolicy: {{ .Values.images.mongo.pullPolicy }}
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "vocard.fullname" $ctx }}
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vocard.fullname" $ctx }}
                  key: mongo-root-password
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
            {{- toYaml .Values.mongo.resources | nindent 12 }}
          livenessProbe:
            exec:
              command: ["mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- with .Values.mongo.storage.storageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongo.storage.size }}
